/** @type {import('tailwindcss').Config} */
// biome-ignore lint/style/noDefaultExport: autogenerated code
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}"
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}

