/** @type {import('tailwindcss').Config} */
// biome-ignore lint/style/noDefaultExport: autogenerated code
export default {
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}"
    ],
    theme: {
        extend: {
            gridTemplateRows: {
                factory: '1fr 8fr'
            },
            gridTemplateColumns: {
                factory: '1fr 2fr'
            }
        },
    },
    plugins: [],
}

