import preact from '@preact/preset-vite';
import { defineConfig } from 'vite';

// https://vitejs.dev/config/
// biome-ignore lint/style/noDefaultExport: autogenerated code
export default defineConfig({
	plugins: [preact()],
});
