import preact from '@preact/preset-vite';
import { defineConfig } from 'vite';
import tsconfigPaths from 'vite-tsconfig-paths';

// https://vitejs.dev/config/
// biome-ignore lint/style/noDefaultExport: autogenerated code
export default defineConfig({
	plugins: [preact(), tsconfigPaths()],
});
